// <auto-generated />
using System;
using Assignment1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Assignment1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251125143538_AddEventDescription")]
    partial class AddEventDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Assignment1.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "KPOP Concert"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "R&B Concerts"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("Assignment1.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTimeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("TicketsAvailable")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EventId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            CategoryId = 1,
                            Description = "",
                            StartTimeDate = new DateTime(2025, 11, 4, 20, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 30m,
                            TicketsAvailable = 7,
                            Title = "Enhypen: WALK THE LINE"
                        },
                        new
                        {
                            EventId = 2,
                            CategoryId = 2,
                            Description = "",
                            StartTimeDate = new DateTime(2025, 12, 4, 19, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 30m,
                            TicketsAvailable = 4,
                            Title = "Sabrina Carpenter: SHORT N'SWEET"
                        },
                        new
                        {
                            EventId = 3,
                            CategoryId = 2,
                            Description = "",
                            StartTimeDate = new DateTime(2026, 1, 4, 21, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 30m,
                            TicketsAvailable = 3,
                            Title = "The Weeknd: After Hours Til Dawn"
                        });
                });

            modelBuilder.Entity("Assignment1.Models.PurchasedEvent", b =>
                {
                    b.Property<int>("PurchasedEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PurchasedEventId"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PurchasedEventId");

                    b.HasIndex("EventId");

                    b.ToTable("PurchasedEvents");
                });

            modelBuilder.Entity("Assignment1.Models.Event", b =>
                {
                    b.HasOne("Assignment1.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Assignment1.Models.PurchasedEvent", b =>
                {
                    b.HasOne("Assignment1.Models.Event", "Event")
                        .WithMany("PurchasedEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Assignment1.Models.Event", b =>
                {
                    b.Navigation("PurchasedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
